                                <!-- Nom:mahamadou Traore
                             **code permanent:TRAM14038709
                                cree le:19-octobre-2010-->
                                <!--pied du page du fichier-->
<hr/>
<p> Travail fait par:Mahamadou Traore TRAM14038709</p>
<table class="bas">
	<tr>
<td class="gauche"><p>
    <a href="http://validator.w3.org/check?uri=referer"><img
        src="http://www.w3.org/Icons/valid-xhtml11"
        alt="Valid XHTML 1.1" height="31" width="88" /></a>
        </p>
</td>

<td class="droite"><p>
    <a href="http://jigsaw.w3.org/css-validator/check/referer">
        <img style="border:0;width:88px;height:31px"
            src="http://jigsaw.w3.org/css-validator/images/vcss"
            alt="CSS Valide !" />
    </a>
</p>
     </td>
</tr>
	
</table>




